apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80      # Port to expose on the service
      targetPort: 80  # Port on the pod to forward traffic to
  type: ClusterIP